
KEY_USER_ID = 'user_id'
KEY_RUN_ID = 'run_id'
KEY_FILE_ID = 'file_id'
KEY_FILE_NAME = 'file_name'
KEY_FILE_TYPE = 'file_type'
KEY_MODULE_ID = 'module_id'
KEY_MODULE_VERSION_ID = 'module_version_id'
KEY_JSON_VERSION_ID = 'json_version_id'
KEY_FILE_LOCATION = 'file_location'
KEY_FILE_EXTENSIONS = 'file_extensions'
